In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
x=np.eye(3)
y=np.ones([3,3])

In [16]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
x@y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
1j*1j

(-1+0j)

In [ ]:
expm()